#### RL HW2 MT19213 Ghanendra

###### Question 2. Write code that solves the linear equations required to find v π ( s ) and generate the values in the table in Figure 3.2 Note that the policy π picks all valid actions in a state with equal probability. Add comments to your code that explain all your steps

In [1]:
# Gridworld
# Possible actions (north, south, east, and west)
# Possible state (location or cells in the grid)
# Considering equiprobable random policy for selection each action with probability 0.25

import numpy as np

# Parameters

G = np.zeros([5,5]) #Grid of size 5x5
Y = 0.9 # gamma
r = 0 # Initial reward = 0
# Initial state selecting randomly
x = [0,1,2,3,4] # array for selecting state
actions = ['n','s','e','w'] # action array
init = np.random.choice(x,2) # randomly select any state
print('Initial state: ',init)
ix = init[0] # x pos of agent in grid
iy = init[1] # y pos of agent in grid

# Function for calculating state value function
def vpi_s(action):
    global ix
    global iy
    global r
    # For state A making transition to A'
    if (ix==0 and iy ==1):
        r = 10 # Reward
        # Expected value for all the four actions
        #G[ix][iy] = 0.25*(r + Y*G[4][1])*4
        G[ix][iy] = (r + Y*G[4][1])
        ix,iy = 4,1 # Updated position

    # For state B making transition to B'
    elif (ix==0 and iy ==3):
        r = 5 # Reward
        # Expected value for all the four actions
        #G[ix][iy] = 0.25*(r + Y*G[4][1])*4
        G[ix][iy] = r + Y*G[2][3]
        ix,iy = 2,3 # Updated position
    else:
        # 0 if hit the grid else grid value
        n = G[ix-1][iy] if ix>0 else 0
        s = G[ix+1][iy] if ix<4 else 0
        e = G[ix][iy+1] if iy<4 else 0
        w = G[ix][iy-1] if iy>0 else 0        
        s = [n,s,e,w] # storing in array

        s_val = 0 # state value
        #s_d = update_pos(action)
        s_d = G[ix][iy]
        # Calculate average from neighboring states
        for i in s:
            # Action within the grid
            if i!=0:
                r=0
                s_val += 0.25*(r + Y*i)
            #Actions at edge in grid
            else:
                r=-1
                s_val += 0.25*(r + Y*s_d)
        G[ix][iy] = s_val

    # Update the position in other states
    update_pos(action)
    # For every instance return grid value
    return G

# Function to update the position based on action
def update_pos(action):
    global ix
    global iy
        
    if (action =='n'): # north
        if (ix>0):
            ix=ix-1
    elif (action =='s'): # south
        if (ix<4):
            ix=ix+1
    elif (action =='e'): # east
        if (iy<4):
            iy=iy+1
    elif (action =='w'): # west
        if (iy>0):
            iy=iy-1     
    
t = 10000 # No. of iterations to converge effectively
for i in range(t):
    # a is the action choosen randomly at time t
    a = np.random.choice(actions,1)
    #s(t) is the state at time t
    s_t = vpi_s(a) # Call vpi(s) function

print('\nGridworld state value function')
np.round(G,1)

Initial state:  [1 1]

Gridworld state value function


array([[ 3.3,  8.8,  4.4,  5.3,  1.5],
       [ 1.5,  3. ,  2.3,  1.9,  0.5],
       [ 0.1,  0.7,  0.7,  0.4, -0.4],
       [-1. , -0.4, -0.4, -0.6, -1.2],
       [-1.9, -1.3, -1.2, -1.4, -2. ]])

###### Question 3. Solve Exercises 3.15 and 3.16.

#### Exercise 3.15

Yes the signs are important because the state A with reward +10 was better compared to state B with reward +5. Second, the sign of A' state which is more negative than B' state indicates its less preferred state to achieve the goal. Third reward with different sign determines action selection for a better policy and goal directed behavior.

##### Proof using Equation 3.8. adding a constant c to each reward at time step t, we have Y is (gamma)discounting factor, expected return is given by

G(t) = R(t+1)+c + Y*[R(t+2)+c] + Y^2 *[R(t+3) + c] + Y^3 * [R(t+4) + c] + . . . . . . 

###### G(t) = R(t+1) + c + Y*R(t+2)+ Y*c + Y^2*R(t+3) + Y^2*c + Y^3*R(t+4) + Y^3*c + . . . .
###### G(t) =  R(t+1) + Y*R(t+2) + Y^2*R(t+3) + Y^3*R(t+4) .....  + c + Y*c + Y^2*c + Y^3*c + ......
###### G(t) =  R(t+1) + Y*R(t+2) + Y^2*R(t+3) + Y^3*R(t+4) .....  + c(1 + Y + Y^2 + Y^3 + ......)

##### Taking c as common in the second expression we have 

G(t) = Summation[k=0 to inf] Y^k * R(t+k+1)   +   c * Summation [k=0 to inf] Y^k

##### Normally we have 0<= Y <=1, if Y is a constant value < 1 , then second term is sum to infinity, therefore

G(t) = Summation[k=0 to inf] Y^k * R(t+k+1)   +   c * 1/( 1 - Y) , where second term evaluates to a constant

Hence, replacing c * 1/( 1 - Y) by a constant Vc.
Now the equation is 
G(t) = Summation[k=0 to inf] Y^k * R(t+k+1)   +  Vc
##### For simplicity we can take first term as Rk(t) = Summation[k=0 to inf] Y^k * R(t+k+1), note Rk(t) is not a constant
G(t) = Rk(t) + Vc

Now value function is given by

vpi(s) = E(pi)[G(t) | S(t) = s] = E(pi) [ Rk(t) + Vc | S(t) = s] , for all small s belongs to state set capital S.
vpi(s) = E(pi)[ Rk(t)| S(t)=s] + E(pi)[ Vc | S(t) = s]

##### As Vc is a contant, expectation of a constant is constant and can be taken out, therefore
vpi(s) = E(pi)[ Rk(t)| S(t)=s] + Vc

##### Vc in terms of c and Y is given by
#### Vc = c/(1-Y)

Hence proved that adding a constant c to all rewards adds a constant Vc to the values of all states.

###### Question 5. Given an equation for v ∗ in terms of q ∗ .

v*(s) = max Summation[s',r] p(s',r|s,a) [r + Y* max q*(s',a')]

###### Question 6. Code policy iteration and value iteration (VI) to solve the Gridworld in Example 4 . 1. Your code must log output of each iteration. Pick up a few sample iterations to show policy evaluation and improvement at work. Similarly, show using a few obtained iterations that every iteration of VI improves the value function. Your code must include the fix to the bug mentioned in Exercise 4 . 4.

In [2]:
#Iterative Policy evaluation
#4x4 Gid world
# Non terminal states = S = {1,2,3,...14}
# Actions = {up, down, right, left}

# Parameters
R = -1 # Reward
# Given its undiscounted episodic task
Y = 1 # gamma = 1
act = ['u','d','r','l'] # action array
# Grid state update array V and V'
V = np.zeros([4,4])
Vd = np.zeros([4,4])
# termination value of loop to get vpi
theta = 0.001
delta = 0
t = 0 # time step

# To log output for 10 iterations
iter = 10
while(t<iter):
    
    for ix in range(0,4):
        ys = 0 if ix>0 else 1
        ye = 4 if ix<3 else 3
        for iy in range(ys,ye):        
            
            # Selecting from array V
            up    = V[ix-1][iy] if ix>0 else V[ix][iy]
            down  = V[ix+1][iy] if ix<3 else V[ix][iy]
            left  = V[ix][iy-1] if iy>0 else V[ix][iy]
            right = V[ix][iy+1] if iy<3 else V[ix][iy]
            m = [up,down,left,right] # storing in array
            s_val = 0
            # Calculate expected value
            for i in m:
                s_val += 0.25 *(R + i)
            #Update new array V'
            Vd[ix][iy] = s_val
            
    # Calculate largest updated value
    delta = np.max(np.abs(V-Vd))
    print('\nDelta: ', delta)
    # Update values from V' into old values array V
    V = np.copy(Vd)
    # Check if delta converges to theta
    t+=1
    print('\nAfter each iteration time step %d V:\n'%t,np.round(V,1))
print('\nEvery iteration improved the value function')


Delta:  1.0

After each iteration time step 1 V:
 [[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]

Delta:  1.0

After each iteration time step 2 V:
 [[ 0.  -1.8 -2.  -2. ]
 [-1.8 -2.  -2.  -2. ]
 [-2.  -2.  -2.  -1.8]
 [-2.  -2.  -1.8  0. ]]

Delta:  1.0

After each iteration time step 3 V:
 [[ 0.  -2.4 -2.9 -3. ]
 [-2.4 -2.9 -3.  -2.9]
 [-2.9 -3.  -2.9 -2.4]
 [-3.  -2.9 -2.4  0. ]]

Delta:  0.96875

After each iteration time step 4 V:
 [[ 0.  -3.1 -3.8 -4. ]
 [-3.1 -3.7 -3.9 -3.8]
 [-3.8 -3.9 -3.7 -3.1]
 [-4.  -3.8 -3.1  0. ]]

Delta:  0.9375

After each iteration time step 5 V:
 [[ 0.  -3.7 -4.7 -4.9]
 [-3.7 -4.5 -4.8 -4.7]
 [-4.7 -4.8 -4.5 -3.7]
 [-4.9 -4.7 -3.7  0. ]]

Delta:  0.89453125

After each iteration time step 6 V:
 [[ 0.  -4.2 -5.5 -5.8]
 [-4.2 -5.2 -5.6 -5.5]
 [-5.5 -5.6 -5.2 -4.2]
 [-5.8 -5.5 -4.2  0. ]]

Delta:  0.8544921875

After each iteration time step 7 V:
 [[ 0.  -4.7 -6.3 -6.7]
 [-4.7 -5.9 -6.4 -6.3]
 [-6.3 -6.4 -5.9 -4.7]
 [-6.7 -6

##### Policy evaluation

In [3]:
def policy_eval(Vd):
    R = -1 # Reward
    Y = 1 # gamma = 1
    theta = 0.001
    delta = 0
    t = 0 # time step
    V = np.copy(Vd)
    t = 0 # time step
    while(1):
        for ix in range(0,4):
            ys = 0 if ix>0 else 1
            ye = 4 if ix<3 else 3
            for iy in range(ys,ye):        

                # Selecting from array V
                up    = V[ix-1][iy] if ix>0 else V[ix][iy]
                down  = V[ix+1][iy] if ix<3 else V[ix][iy]
                left  = V[ix][iy-1] if iy>0 else V[ix][iy]
                right = V[ix][iy+1] if iy<3 else V[ix][iy]
                m = [up,down,left,right] # storing in array
                s_val = 0
                # Calculate expected value
                for i in m:
                    s_val += 0.25 *(R + i)
                #Update new array V'
                Vd[ix][iy] = s_val

        # Calculate largest updated value
        delta = np.max(np.abs(V-Vd))
        # Update values from V' into old values array V
        V = np.copy(Vd)
        # Check if delta converges to theta
        t+=1
        if(delta < theta):
            break
    print('Delta (%.5f) < theta (%.3f)'%(delta,theta))
    print('After time step t=%d value V ~ V(pi) \nV:\n'%t,np.round(V,1))
    return V
Vd = np.zeros([4,4])
V = policy_eval(Vd)

Delta (0.00098) < theta (0.001)
After time step t=131 value V ~ V(pi) 
V:
 [[  0. -14. -20. -22.]
 [-14. -18. -20. -20.]
 [-20. -20. -18. -14.]
 [-22. -20. -14.   0.]]


###### Policy Iteration

In [4]:
# Policy iteration

V = np.zeros([4,4])
Vd = np.zeros([4,4])
t = 0 # time step
while(1):
    for ix in range(0,4):
        ys = 0 if ix>0 else 1
        ye = 4 if ix<3 else 3
        for iy in range(ys,ye):        
            
            # Selecting from array V
            up    = Vd[ix-1][iy] if ix>0 else Vd[ix][iy]
            down  = Vd[ix+1][iy] if ix<3 else Vd[ix][iy]
            left  = Vd[ix][iy-1] if iy>0 else Vd[ix][iy]
            right = Vd[ix][iy+1] if iy<3 else Vd[ix][iy]
            m = [up,down,left,right] # storing in array
            s_val = 0
            # Calculate expected value
            for i in m:
                s_val += 0.25 *(R + i)
            #Update new array V'
            Vd[ix][iy] = s_val
            
    # Calculate largest updated value
    delta = np.max(np.abs(V-Vd))
    # Update values from V' into old values array V
    V = np.copy(Vd)
    # Check if delta converges to theta
    t+=1
    if(delta < theta):
        break
print('Delta (%.5f) < theta (%.3f)'%(delta,theta))
print('After time step t=%d value V ~ V(pi) \nV:\n'%t,np.round(V,1))
print('\n Using only V\' it converges faster in lesser time step' )


Delta (0.00097) < theta (0.001)
After time step t=88 value V ~ V(pi) 
V:
 [[  0. -14. -20. -22.]
 [-14. -18. -20. -20.]
 [-20. -20. -18. -14.]
 [-22. -20. -14.   0.]]

 Using only V' it converges faster in lesser time step


###### Policy iteration and improvement

In [5]:
# Policy evaluation
# Policy improvement

def policy_improv(Vd):
    V = np.copy(Vd)
    policy_stable = True
    for ix in range(0,4):
        ys = 0 if ix>0 else 1
        ye = 4 if ix<3 else 3
        for iy in range(ys,ye):        

                # Selecting from array V
            up    = V[ix-1][iy] if ix>0 else V[ix][iy]
            down  = V[ix+1][iy] if ix<3 else V[ix][iy]
            left  = V[ix][iy-1] if iy>0 else V[ix][iy]
            right = V[ix][iy+1] if iy<3 else V[ix][iy]
            m = [up,down,left,right] # storing in array
            s_val = 0
            # Calculate action which returns max value
            s_val = np.max(m)
            #Update new array V'
            Vd[ix][iy] = s_val
    return Vd

Vp = np.zeros([4,4])

for i in range(1,2):
    Ve = policy_eval(Vp)
    Vp = policy_improv(Ve)
    print('\n After %d improvement:\n'%i,np.round(Vp,1))


Delta (0.00098) < theta (0.001)
After time step t=131 value V ~ V(pi) 
V:
 [[  0. -14. -20. -22.]
 [-14. -18. -20. -20.]
 [-20. -20. -18. -14.]
 [-22. -20. -14.   0.]]

 After 1 improvement:
 [[  0.   0. -14. -20.]
 [  0. -14. -18. -14.]
 [-14. -18. -14.   0.]
 [-20. -14.   0.   0.]]


###### Question 8. When we defined a Markov Decision Process (MDP) we explicitly captured, using probability mass functions (PMF), the fact that the random variable R t +1 is dependent on the state S t and the action A t . Is the random variable R t +2 dependent on S t and A t ? Support your answer using the PMFs we used to define a MDP. [Hint: Start with the conditional PMF of R t +2 conditioned on S t and A t .]

In [ ]:
Based on the markov property considering rewards are received at discrete time steps at sequential stages.

Yes Reward R(t+2) depends on St and At.
PMF of [ R(t+2) | St = s1, At = a1 ]

###### Question 10. We know that the state-value function v π ( s ) = E [ G t |S t = s ]. Use this definition of v π ( s ) to derive the Bellman equation for v π ( s ) for all s ∈ S . The Bellman equation will use the PMF corresponding to the policy π and the PMF p ( s 0 , r|s, a ) and will provide a recursive method of calculating v π ( s ).

In [ ]:
v π(s) = Eπ[Gt|St=s]
from Gt = R(t+1) + Y*G(t+1) put in above equation

v π(s) = Eπ[R(t+1) + Y*G(t+1)|St=s]

v π(s) = Eπ[R(t+1)|St=s] + Y*Eπ[G(t+1)|St=s]


###### Question 11. Suppose an agent receives the sequence of rewards R 1 = 2, R 2 = − 1, R 3 = 10, and R 4 = − 3. Calculate the γ discounted return/reward for each time step for γ = 0 . 5. Also show that, if an agent receives a constant reward c , at every time step, for γ < 1, the infinite horizon discounted return is given by

In [22]:
#Considering the rewards
#Return Gt = R(t+1) + Y*R(t+2) + Y^2*R(t+3) + Y^3*R(t+4)

# Rewards
R1 = 2
R2 = -1
R3 = 10
R4 = -3
#discounted factor
Y = 0.5

#Rewards For each time step

G0 = R1 + Y*R2 + Y**2*R3 + Y**3*R4
print('G0',G0)

G1 = R2 + Y*R3 + Y**2*R4
print('G1',G1)

G2 = R3 + Y*R4
print('G2',G2)

G3 = R4
print('G3',G3)

# If Y<1, receiveing a constant reward
#Gt = c + Y*c + Y^2*c + Y^3*c + Y^4*c + Y^5*c + .....
#Gt = c*(1 + Y + Y^2 + Y^3 + Y^4 + Y^5 + ....) 
#Using sum to infinity its given by
#Gt = c * 1/ (1-Y) # Put Y = 0.5
#Gt = 2*c

# Infinite horizon discounted return
Gt = '2c'
print('Gt',Gt)

G0 3.625
G1 3.25
G2 8.5
G3 -3
Gt 2c


###### Question 12. Suppose you are given the optimal state-value function v ∗ ( s ), for all s ∈ S . How will you find the optimal policy? Show your steps.

* Given v*(s) optimal state value function
0. v*(s) = max vπ(s) from (3.15)
1. #From Bellman optimality equation we have
2. v*(s) = max(a) Σ[s',r] p(s',r|s,a)[r+Yv*(s')]
3. To find π*(s), from 4.9 we have
4. π'(s) = argmax(a)Σ p(s',R|s,a)[r + Y*v π(s')]
5. therefore for optimal policy, each action return the maximum value which is optimal value function
6. π*(s) = argmax(a)Σ p(s',R|s,a)[r + Yv*(s')]

###### Question 13. A server requires information from a sensor. The server would like the information to be fresh. However, there is a cost to querying information from the sensor. Specifically, the state at the server can be either fresh or stale. The former indicates that the information at the server about the sensor is fresh and the latter indicates that it is stale. At any time, the server may choose to query or remain silent. A query makes stale information fresh with probability 0 . 8 and fresh information stale with probability 0 . 1. Staying silent keeps stale information stale with probability 1 and makes fresh information stale with probability 0 . 5. Also, a query when current information at the server is stale costs 8 dollars. Otherwise, it costs 4 dollars. Staying quiet has a reward of 4 dollars.

###### 1. Draw and/or tabulate the MDP

* For server
* States = {stale, fresh}
* Actions = {query, silent}



| S no. | State(s) | Action(a) | State(s') | Probability (p) | Reward (r)|
| --- | --- | --- | --- | --- | --- |
|1. | Stale | Querry | Fresh | 0.8 | -8 |
|2. | Stale | Querry | Stale | 0.2 | -8 |
|3. | Stale | Silent | Stale | 1 | 4 |
|4. | Fresh | Querry | Stale | 0.1 | -4 |
|5. | Fresh | Querry | Fresh | 0.9 | -4 |
|6. | Fresh | Silent | Fresh | 0.5 | 4 |
|7. | Fresh | Silent | Stale | 0.5 | 4 |

###### 2. Consider a finite horizon problem in which the server gets to optimize costs over three time steps. Assume that if at the end of the three time steps the server has stale information it pays a cost of 10, else it receives a reward of 10. Also, assume that future costs are discounted with a factor 1 / 2. Calculate the optimal costs for every starting state. Calculate the optimal policy. Show all your steps. Guesses and intuition will bring you unbounded costs.

In [ ]:
#Solved in uploaded pdf.

###### 3. Suppose the server is to optimize for ever and is looking for a stationary policy. Write down the first four iterations of value iteration that will help the server get closer to a stationary policy. Do the same for policy iteration (where one iteration includes evaluation and improvement). Clearly identify each iteration.

In [ ]:
#Solved in uploaded pdf.    

###### Question 14. Assume an infinite horizon discounted costs problem. Prove that the policy improvement step either improves the current policy or the current policy is optimal. Show all your steps and support them using the properties of dynamic programming.

#Policy improvement in infinite horizon discounted costs problem.

#Proof.
#From infinite horizon discounted costs expected return becomes a constant
#From 4.7 considering policies π and π' and 4.8 such that we have
If q π(s,π'(s)) >=v π(s) then vπ'(s) >= vπ(s)

v π(s) <= E π'[ R(t+1) + YR(t+2) + Y^2*R(t+3) + Y^3R(t+4) + ... | St = s]
#Considering All the rewards as R for our grid world example, we have
0. v π(s) <= E π'[ R + YR + Y^2*R + Y^3R + ... | St = s]
1. v π(s) <= E π'[ R/(1-Y) | St = s], from horizon discounted costs
2. Considering R/(1-Y) = some constant C
3. v π(s) <= E π'[C | St = s] = C* E π'[St = s]
4. v π(s) <= v π'(s)
5. Similar from Q11, as Expected return Gt = 2c
6. π'(s) = argmax(a)Σ p(s',R|s,a)[r + Y*vπ(s')]
7.  π'(s) = argmax(a)Σ p(s',R|s,a)[r + Y*C]
8. If π' is better than π, π'(s) > π(s)
9. If π' is equal to π, then v π = v π'
10. So, we obtain v π'(s) = max Σ p(s',R|s,a)[r + Y*C]
11. Hence, the policy improvement step is either better or the current policy will be optimal.
12. π'(s) <-- argmax(a)Σ p(s',R|s,a)[r + Y*v π'(s)]
13. So old-action != π'(s)m then policy stable = False or old-action = π'(s), policy stable = True
14. V ~ v* and π = π*

###### Question 15. The Stairwell: A stairwell connects the ground floor (G) of a palace with its first floor (F). It consists of a total of n steps, indexed 1 , 2 , . . . , n , with step 1 close to G and step n connected to F. A robot may start in any step and must learn to decide on whether it should go to F or to G. Both F and G are terminal states. The robot gets a reward of 2 with probability 0 . 5, and 0 otherwise, when it descends from step i to i− 1, 1 < i ≤ n . It also gets a reward of 1 on going from step 1 to G. On the other hand, the robot pays a cost of 1 (reward − 1) when it moves from step i to i + 1, 1 ≤ i < n . Finally, the robot gets a bumper reward of 2 n when it goes from step n to F. The robot can only take one step at a time. Start with a policy in which the robot goes up or down a step in the stairwell with probability 0 . 5. Draw the corresponding MDP for n = 2. Use policy iteration to find the optimal policy for n = 2. Show all your iterations and explain them. How does the number of iterations increase with n ? Explain your answer. Assume a discount factor of 1.

In [ ]:
#Solved in uploaded pdf.